### ISSUE TITLE
Test data: `dm_metabolic`

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiralmetabolic#12]
### Background Information

We need to create an `{admiralmetabolic}` version of `pharmaversesdtm::dm` which contains a small subset (5?) of the patients in the full dm dataset, so that we can use the same 5 patients across all of our new test data.

This dataset will eventually be moved to `{pharmaversesdtm}`, but for the moment we will create it within `{admiralmetabolic}`.

Check out [pharmaversesdtm repo](https://github.com/pharmaverse/pharmaversesdtm) for inspiration.

### Definition of Done

- [ ] top-level `data_raw` folder created to house `dm_metabolic`, i.e. the script that generates our metabolic version of `dm`
- [ ] `dm_metabolic` program set up. program should read in `dm`, keep only a few (5?) patients. 
- [ ] Review all `dm_metabolic` variables to see if any changes are required.
- [ ] New `dm_metabolic` dataset documented in `data.R`

**Comment by AndersAskeland** [comment]
I am wondering if it would make sense to change the pre-defined treatment / ARM? The DM example from `pharmaversesdtm` have three treatment arms (Xanomeline Low, Xanomeline High, and Placebo). If we change, I would argue that it should be something non-descriptive (i.e. insulin, or weight loss drug A). 

Furthermore, I am contemplating on weather to include a screen failure participant in the dataset. I notice that most Admiral extension don't have any screen failures, but would it make sense for the vignettes to have something to sort away? Or do we consider this to be covered in `admiral` base?

**Comment by manciniedoardo** [comment]
> I am wondering if it would make sense to change the pre-defined treatment / ARM? The DM example from `pharmaversesdtm` have three treatment arms (Xanomeline Low, Xanomeline High, and Placebo). If we change, I would argue that it should be something non-descriptive (i.e. insulin, or weight loss drug A).
> 
> Furthermore, I am contemplating on weather to include a screen failure participant in the dataset. I notice that most Admiral extension don't have any screen failures, but would it make sense for the vignettes to have something to sort away? Or do we consider this to be covered in `admiral` base?

@AndersAskeland Agree that changing the arm makes sense, happy to go with one of your suggestions.

In terms of screen failure, generally we don't include them, so I would continue down that path unless there was a reason specific to this TA as to why we might want to include that type of record.
