### ISSUE TITLE
Questionnaire research: Identify questionnaires of interest and investigate licensing/purpose

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiralmetabolic#13]
### Background Information

Two possible questionnaire datasets specific to our TA are the UWQoL (Impact of Weight on Quality of Life) and TFEQ (Three-Factor Eating Questionnaire), but there could definitely be others.

Let's use this issue to share our research findings around each of the questionnaires. This could include:

- Licensing (are they free to use)?
- Why these questionnaires are of interest for admiralmetabolic
- When implemented in something like an ADQS, are there any steps that are non-standard or unique to these questionnaires? This could be special computed scores, special processing, etc.

Please share any findings as soon as you have them to not duplicate any work.

### Definition of Done

Obtain a detailed understanding of each of the questionnaires, enabling us to set out 

- what test data we need to create
- what templates we need to create
- what vingettes we need to create
- *why* we are doing this, i.e. what is unique to the TA that warrants inclusion into {admiralmetabolic}?

**Comment by AndersAskeland** [comment]
I've been trying to investigate UWQoL, and it appears to have a restrictive license. The licence is held by [Pattern Health ](https://pattern.health/exchange/iwqol-impact-of-weight-on-quality-of-life/). It is no specific information about open source use, but a "[Reference work entry](https://link.springer.com/referenceworkentry/10.1007/978-0-387-78665-0_12)" states that the licensing fee varies according to use. Hence, if we decide that this questionnaire is relevant, someone would need to contact Pattern Health. 

Furthermore, there seems to be several versions, where there is one specifically developed for clinical trials (IWQOL-Lite-CT). Pattern Health's website also states "FDA qualification for the IWQOL-Lite-CT is being sought for use in clinical trials to support product-labeling claims in new obesity treatments, including medications.".

**Comment by manciniedoardo** [comment]
> I've been trying to investigate UWQoL, and it appears to have a restrictive license. The licence is held by [Pattern Health ](https://pattern.health/exchange/iwqol-impact-of-weight-on-quality-of-life/). It is no specific information about open source use, but a "[Reference work entry](https://link.springer.com/referenceworkentry/10.1007/978-0-387-78665-0_12)" states that the licensing fee varies according to use. Hence, if we decide that this questionnaire is relevant, someone would need to contact Pattern Health.
> 
> Furthermore, there seems to be several versions, where there is one specifically developed for clinical trials (IWQOL-Lite-CT). Pattern Health's website also states "FDA qualification for the IWQOL-Lite-CT is being sought for use in clinical trials to support product-labeling claims in new obesity treatments, including medications.".

Thanks @AndersAskeland - if @Sonali-netizen or someone else confirms that this is an important scale then maybe we could investigate further and contact them.

**Comment by Sonali-netizen** [comment]
IWQOL-Lite-CT is used in Obesity related clinical trials, but it could also be used for other metabolic related treatments/medications so having this scale would be helpful. The important part of this questionnaire is the calculation of composite scores.

**Comment by manciniedoardo** [comment]
> IWQOL-Lite-CT is used in Obesity related clinical trials, but it could also be used for other metabolic related treatments/medications so having this scale would be helpful. The important part of this questionnaire is the calculation of composite scores.

How are the composite scores calculated?

**Comment by Sonali-netizen** [comment]
These composite scores are calculated based on the responses to the questions. The responses are categorized and mapped to a number, for instance, a response 'NEVER' would be mapped to 1 and 'ALWAYS' to 5. Considering these numerical values, the AVAL is calculated by taking 100 times the result of the expression: the difference between the maximum response scale value and the mean, divided by the difference between the maximum response scale value and the minimum response scale value. We need to check if there are other variations to this derivation.

**Comment by manciniedoardo** [comment]
@Sonali-netizen thanks. Perhaps you could check:

- Whether there are indeed any other variations to this derivation
- To what extent this is covered in {admiral}'s standard questionnaire vignette

The latter point would inform whether we'd need a fully separate vignette/template or could just lean into existing documentation/template.

**Comment by manciniedoardo** [comment]
@Sonali-netizen any updates on this?

**Comment by manciniedoardo** [comment]
Update: the IWQoL-lite-CT questionnaire was discussed in today's team call.

- It was noted that this should be our primary questionnaire of focus for {admiralmetabolic}
- We still need to identify the extent of programming required for an ADaM dataset (@Sonali-netizen , Mikkel, @AndersAskeland to help out on this front)
- We need to contact Pattern Health and request permission to set up test data (@manciniedoardo to do this)

**Comment by Sonali-netizen** [comment]
> @Sonali-netizen any updates on this?

I looked up the standard questionnaire vignette and none of the cases/questionnaires discussed in that can be used for IWQoL. We would need to write a function for the computation of scores part, as the IWQoL questionnaire would have 20 questions and maybe all of them would be answered or only some of them would be answered. Depending on that we need to calculate the composite scores and then transform the composite average to the 0-100 scale. The compute_scale may come close to what we would require for IWQoL but then for the transformation of the composite average, there is an algorithm involved.

**Comment by manciniedoardo** [comment]
Thanks @Sonali-netizen - good to know!

**Comment by manciniedoardo** [comment]
@Sonali-netizen shared with me the following code and text to give an example of how to work with the IWQOL-lite-CT scores. I leave this here as it could be a good basis for our vignette and template, pending authorisation to use IWQOL-lite-CT.

The derivation for the IWQoL dataset would pretty much follows the process as described in the vignette [Creating a BDS Finding ADaM ](https://pharmaverse.github.io/admiral/articles/bds_finding.html) until the point the derivation of the composite scores starts, the SDTM data is read and processed for the DATE and TIME variables, VISIT variables, PARAM, PARAMCD etc. and eligibility variables like ANELFL etc.

For the derivation of composite scores, I have used the following code. This code is not validated yet.

````
#' There are 20 questions in the IWQoL questionnaire. In SDTM data, the QSTESTCD has value IWQOL301 to IWQOL320. 
#' So depending on the questions we group them into four categories, Psychosocial, Physical, Physical function and Total.

iwqol_coding <- data.frame(
  measure = toupper(c(
    rep("iwqol_ct_20_psychosocial_score", 13),
    rep("iwqol_ct_20_physical_score", 7),
    rep("iwqol_ct_20_physical_function_score", 5),
    rep("iwqol_ct_20_total_score", 20)
  )),
  variable = c(
    "IWQOL306", "IWQOL307", "IWQOL308", "IWQOL309", "IWQOL310", "IWQOL311", "IWQOL312", "IWQOL313", "IWQOL314", "IWQOL315", "IWQOL318", "IWQOL319", "IWQOL320",
    "IWQOL301", "IWQOL302", "IWQOL303", "IWQOL304", "IWQOL305", "IWQOL316", "IWQOL317",
    "IWQOL301", "IWQOL302", "IWQOL303", "IWQOL316", "IWQOL317",
    "IWQOL301", "IWQOL302", "IWQOL303", "IWQOL304", "IWQOL305", "IWQOL306", "IWQOL307", "IWQOL308", 
"IWQOL309", "IWQOL310", "IWQOL311", "IWQOL312", "IWQOL313", "IWQOL314", "IWQOL315", "IWQOL316", 
"IWQOL317", "IWQOL318", "IWQOL319", "IWQOL320"
  ),
  value = c(1:13, 1:7, 1:5, 1:20),
  category = c(rep("Psychosocial", 13), rep("Physical", 7), rep("Physical Function", 5), rep("IWQOL-Lite-CT Total", 20))
)


#' The responses to the questions are in two types:
#' one type is ("NEVER", "RARELY", "SOMETIMES", "USUALLY", "ALWAYS")
#' another type is ("NOT AT ALL TRUE", "A LITTLE TRUE", "MODERATELY TRUE", "MOSTLY TRUE", #"COMPLETELY TRUE")
#' The responses have to be coded to a numerical value so tht we can proceed with the #computation of scores.

iwqol_formats <- list(
  tmpfmt1a = setNames(c(1, 2, 3, 4, 5), c("NEVER", "RARELY", "SOMETIMES", "USUALLY", "ALWAYS")),
  tmpfmt1b = setNames(c(1, 2, 3, 4, 5), c("NOT AT ALL TRUE", "A LITTLE TRUE", "MODERATELY TRUE", "MOSTLY TRUE", "COMPLETELY TRUE"))
)

der_01 <- val_f %>%
  mutate(
    QSVALUE = if_else(QSTESTCD %in% c("IWQOL316", "IWQOL317", "IWQOL318", "IWQOL319", "IWQOL320"),
                      as.numeric(factor(AVALC, levels = c("NOT AT ALL TRUE", "A LITTLE TRUE", "MODERATELY TRUE", "MOSTLY TRUE", "COMPLETELY TRUE"))),
                      as.numeric(factor(AVALC, levels = c("NEVER", "RARELY", "SOMETIMES", "USUALLY", "ALWAYS")))
    ),
    AVAL = if_else(!is.na(QSVALUE), QSVALUE, AVAL)
  )

#' Below is the function where we pass certain parameters: the maximum and minimum possible score, 
req_frac_items is rate of minimum available answered items to calculate score

compscoreadqsiwql <- function(df, max_resp_scale_val, min_resp_scale_val, req_frac_items, composite_name, iwqol_coding) {
  iwqol_coding_comp <- iwqol_coding %>%
    filter(measure == !!composite_name) %>%
    mutate(
      req_num_nmiss_items = ceiling(n() * req_frac_items),
      tot_num_items = n()
    )


  composite_1 <- left_join(df, iwqol_coding_comp,
                           by = c("QSTESTCD" = "variable")
  ) %>%
    filter(ANELFL == "Y") %>%
    filter(!is.na(value))

  composite_2_mean <- composite_1 %>%
    group_by(USUBJID, AVISITN) %>%
    summarize(
      n = n(),
      mean = mean(AVAL) ,  .groups = "drop"
    )

  composite_3_aval <- composite_2_mean %>%
    mutate(
      ANELFL = if_else(n > ceiling(req_frac_items), "Y", NA_character_),
      AVAL = if_else(n > ceiling(req_frac_items),
                     100 * ((max_resp_scale_val - mean) /
                              (max_resp_scale_val - min_resp_scale_val)),
                     NA_real_
      ),
      TOPICCD = if_else(n > ceiling(req_frac_items), composite_name, NA_character_)
    )


  comp_1 <- composite_1 %>%
    select(-c("AVAL", "TOPICCD", "ANELFL", "QSTESTCD", "QSORRES")) %>%
    group_by(USUBJID, AVISITN) %>%
    filter(row_number() == 1) %>%
    ungroup()


  output <- left_join(comp_1,
                      composite_3_aval %>% select(USUBJID, AVISITN, TOPICCD, ANELFL, AVAL),
                      by = c("USUBJID", "AVISITN")
  ) %>%
    mutate(AVALU = "Score")
}

min_resp_scale_val <- 1
max_resp_scale_val <- 5
req_frac_items <- 0.5
composite_name <- "IWQOL_CT_20_PSYCHOSOCIAL_SCORE"


PsycSoc <- compscoreadqsiwql(
  der_01, max_resp_scale_val, min_resp_scale_val,
  req_frac_items, composite_name, iwqol_coding
)

min_resp_scale_val <- 1
max_resp_scale_val <- 5
req_frac_items <- 0.5
composite_name <- "IWQOL_CT_20_PHYSICAL_SCORE"

Phys <- compscoreadqsiwql(
  der_01, max_resp_scale_val, min_resp_scale_val,
  req_frac_items, composite_name, iwqol_coding
)
#' Similarly derive the composite scores for the other two categories and then combine all of the #datasets together
der_02 <- bind_rows(PsycSoc, Phys, PhysFun, Total)
```

**Comment by manciniedoardo** [comment]
Hi all, as an update, I met with representative from Pattern Health (IWQOl-Lite-CT license holder). They confirmed both the questionnaire questions and the method of analysis are intellectual property. As such they are unlikely to give go ahead to include any test data or reveal how analysis should be done (final confirmation soon). Once the confirmation comes through we can just close this issue.

**Comment by AndersAskeland** [comment]
That is too bad about the IWQOI questionnaire. 

I guess we still have the possibility of pursuing the three factor eating questionnaire (TFEQ). While I can't find any specific information about the licencing for that, at least it appears to be publicly available, and we might have better luck with getting permission to use it.

Are you also familiar with this questionnaire @Sonali-netizen ? If yes, do you think it should be something we should pursue, or which can be handled by base Admiral functions?

**Comment by kathrinflunkert** [comment]
That's really unfortunate regarding the IWQOI questionnaire.

We are not using the three factor eating questionnaire (TFEQ) but rather the Control of Eating Questionnaire (CoEQ) which seems to be available without licencing:
https://licensing.leeds.ac.uk/product/control-of-eating-questionnaire-coeq
Are you using this one as well?

**Comment by AndersAskeland** [comment]
I am not entirely sure, perhaps @starnas or @Sonali-netizen know?

**Comment by manciniedoardo** [comment]
@starnas @Sonali-netizen any updates on this?

**Comment by Sonali-netizen** [comment]
No, I have not worked on the TFEQ questionnaire.

**Comment by MikkelChr** [comment]
@kathrinflunkert we are using CoEQ and TFEQ at NN. So this could be an opportunity. 

In TFEQ and COEQ the values are categories and scored in groups of questions relating to feeling and cravings. I think it would be useful with functions (or vignettes?) for calculating these if allowed.

**Comment by AndersAskeland** [comment]
Thanks  @MikkelChr . Would you be able to write some more about how the values are categorized and grouped, perhaps with a small example?

**Comment by manciniedoardo** [comment]
@Sonali-netizen @MikkelChr could you also please check what licensing constraints apply here?

**Comment by manciniedoardo** [comment]
@MikkelChr any updates please? Maybe @Sonali-netizen can help here?

**Comment by starosto** [comment]
I am checking the licensing case for some of the questionnaires. I will have an update tomorrow. I see that we also use TFEQ but rather do not use CoEQ.

**Comment by manciniedoardo** [comment]
@starosto did you end up finding out?

**Comment by starosto** [comment]
@manciniedoardo I replied on slack

**Comment by MikkelChr** [comment]
> @MikkelChr For the CoEQ are you using the 21-item version or the 19-item version (which is essentially only items 1 to 19 from the 21-item version)? And is the collected raw item data on a range from 0 to 100 or from 0 to 10 (full integers only)? We are having some confusions on our end here about these two ways of collecting the data.

I guess we will have to clear that up before implementing anything. I have  values from 1-10 all the way it seems.

**Comment by starosto** [comment]
I checked what COAs could be useful for our studies and did some research on where licenses are required.
Some COAs are free for academia/non-profit research but the question arise whether since we represent our companies, is it really a “non-profit research” (from a legal point of view). I am consulting this and will let you know when I get an answer.
Below I am pasting the COAs and license information that I found on the website https://eprovide.mapi-trust.org/
To see full license information on that website, you need to have a subscription, but I investigated with the help of a colleague's account.
C-SSRS – license owner: RFMH - With fees for commercial/pharmaceutical companies
IWQOL -  license owner: Duke - With fees for academic/non profit research/ With fees for commercial/pharmaceutical companies:
PSQI -  license owner: University of Pittsburgh. It is not necessary to contact the Office of Technology Management at the University of Pittsburgh to use the PSQI for academic clinical research.
SF36 V2.0 ACUTE –  license owner: Quality Metric - With fees for commercial/pharmaceutical companies
NASH-CHECK –  license owner: RWS/Novartis
CLDQ NAFLD-NASH -  license owner: CORLD - With fees for commercial/pharmaceutical companies
PHQ-9 – public available
TFEQ -  license owner: Pearson - with fees for academic/non profit research/ commercial/pharmaceutical companies
CoEQ –  license owner: Free access upon registration all academic use and non-profit research/ With fees for commercial/pharmaceutical companies
PGI-S – public available
KCCQ – With fees for commercial/pharmaceutical companies

**Comment by manciniedoardo** [comment]
Decision from today's call:

- @kathrinflunkert to invesitage about feasibility of inclusion of CoEQ data/vignette (similar to what I did for IWQoL)
- re-evaluate after that whether it's worth pursuing other questionnaires or whether we should focus our energies elsewhere

**Comment by kathrinflunkert** [comment]
I sent an email to Leeds university regarding the CoEQ just now. Will update here when I hear back from them.

**Comment by manciniedoardo** [comment]
Update from @kathrinflunkert in today's call: received all-clear from University of Leeds to create test data, vignette and template, as long as we formally apply for a non-commercial license. We also need to include text at the top of our vignette, template and test dataset documentation specifying that _UoLeeds is the license holder and any parties wishing to use the CoEQ questionnaire need to purchase the license (at the appropriate link)_.

All CoEQ discussion should now go in the following issues:

- Test data:  #39 
- Vignette:  #40 (on hold until test data created)
- Template: #41 (on hold until vignette created)

**Comment by manciniedoardo** [comment]
@pharmaverse/admiralmetabolic I will close this issue now that we can likely focus our efforts on one questionnaire only. If any other questionnaires are of interest, please raise at our team meeting or with a new issue.
