### ISSUE TITLE
Bug: Several CI/CD pipeline fails because "actions/upload-artifact: v2" is depreciated

### ISSUE THREAD

**Issue by AndersAskeland** [pharmaverse/admiralmetabolic#27]
### What happened?

The download artifact pipeline action is depreciated, causing a variety of CI/CD pipelines to fail (check, code-style, lint, code coverage). See notice from github here: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/

Pipeline run example: https://github.com/pharmaverse/admiralmetabolic/actions/runs/10826742018/job/30038358115

Unsure if we should fix it here, or wait for admiral base to implement a solution.

**Comment by AndersAskeland** [comment]
What are your thoughts @manciniedoardo ?

**Comment by manciniedoardo** [comment]
@AndersAskeland looking into it from the admiral side as we inherit all our CICD from the parent repos.

**Comment by manciniedoardo** [comment]
fix proposed here: https://github.com/pharmaverse/admiralci/pull/194

**Comment by AndersAskeland** [comment]
Fix merged into {admiralci} and our workflow is now working again.

**Comment by manciniedoardo** [comment]
![image](https://github.com/user-attachments/assets/5e5cb9a4-4c03-4700-bcbf-56eddf9ad1ed)
