### ISSUE TITLE
Documentation: Update ADVS vignette

### ISSUE THREAD

**Issue by Siddhesh2097** [pharmaverse/admiralmetabolic#28]
### Background Information

Several updates are needed to the ADVS vignette. This includes:

- Use new {admiral} AVALCAT derivation function.
    - Currently there is nothing specific in {admiral} for AVALCAT derivation so ADVS template and vignette just go about it using tidyverse tools. This will change once the functionality is added to {admiral} - [see here](https://github.com/pharmaverse/admiral/issues/2480). **Update**: This is now added to Admiral dev version and can be completed.
- Use `restrict_derivation()` in conjunction with `derive_vars_crit_flag()`.
    - Without using `restrict_derivation` the crit flag is present on all PARAMCD's. See ADVS template for how to implement.
 - Update PARACAT1 to "Anthropometric measurements" for PARAMN in range 1-5. This would also close #32 

### Definition of Done

Update vignette as per specification defined above.

**Comment by manciniedoardo** [comment]
Hi @Siddhesh2097, how is this going?

**Comment by AndersAskeland** [comment]
I am changing this issue to include all required ADVS updates.

**Comment by Siddhesh2097** [comment]
Hi @manciniedoardo , I completely lost track of this issue. Will start working on this.
