### ISSUE TITLE
Chrome tab icon shows pharmaverse hex rather than admiralmetabolic hex

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiralmetabolic#3]
### Please select a category the issue is focused on?

Other

### Let us know where something needs a refresh or put your idea here!

See admiralophtha:
![image](https://github.com/pharmaverse/admiralmetabolic/assets/53403957/cce05eda-796c-4c83-8480-af4c98bddac4)

Compared to admiralmetabolic:
![image](https://github.com/pharmaverse/admiralmetabolic/assets/53403957/fb535bc1-bb63-47fa-99cd-42ceb45542dd)

Follow the same process as was done for [this corresponding issue](https://github.com/pharmaverse/admiralophtha/issues/225) to update.

**Comment by manciniedoardo** [comment]
@kathrinflunkert could you please share how you went about this? @jwang-lilly did this same task for admiralneuro and ended up writing some code to generate the favicon of the right size, so I'm interested if you did things differently and if we should save Jian's code somehere

**Comment by kathrinflunkert** [comment]
@manciniedoardo I think I actually just did it in Paint, i.e. open the image, reduce the size to what is needed, and save. 😊

**Comment by manciniedoardo** [comment]
Thanks @kathrinflunkert  - in that case, @jwang-lilly maybe we should make the code you used to do this "programmatically" available in admiraltemplate. I'll make an issue in that repo.
