### ISSUE TITLE
Documentation:  Update ADVS metabolic vignette lookup table PARCAT1

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiralmetabolic#32]
### Let us know where something needs a refresh or put your idea here!

Suggestion from @starosto: In the lookup table (code line 113-115) for the parameters BMI, HIPCIR, WSTCIR, the variable `PARCAT1` has the value “Subject Characteristic”, and since weight and circumferences are also measured during the study, I would assign “Vital Signs" instead.

Suggestions from today's call:

- Anthropometric measurements
- Vital signs
- Subject characteristics (i.e. keep the same)

**Comment by manciniedoardo** [comment]
My personal view here is that Anthropometric measurements is the best choice.

**Comment by manciniedoardo** [comment]
@pharmaverse/admiralmetabolic thoughts?

**Comment by starosto** [comment]
We do not use ADVS.PARCAT1 variable. For all parameters with PARCAT1 = “Subject Characteristic” I suggest “Anthropometric measurements” or “Body measurements”

**Comment by kathrinflunkert** [comment]
Another vote for PARCAT1 = "Anthropometric measurements" from me.

**Comment by gandbasel** [comment]
Sounds appropriate to me as well

**Comment by AndersAskeland** [comment]
Can you take this @Siddhesh2097 in combination with #28 ?

**Comment by Siddhesh2097** [comment]
Yes @AndersAskeland . Will work on this
