### ISSUE TITLE
Feature Request:  Change data load method in `vs_metabolic.R` and `dm_metabolic.R`

### ISSUE THREAD

**Issue by AndersAskeland** [pharmaverse/admiralmetabolic#34]
### Feature Idea

Instead of using `data("")` for loading data, change to `packagename::data` in `vs_metabolic.r` and `dm_metabolic.r`.

This is the recommended way of loading data from packages.

### Relevant Input

NA

### Relevant Output

NA

### Reproducible Example/Pseudo Code

For instance in `vs_metabolic.r` change:

```r
data("vs")

data("dm_metabolic")
```

to

```r
pharmaversesdtm::vs

admiralmetabolic::dm_metabolic
```

**Comment by cosmiiccat** [comment]
Hi @AndersAskeland ,
I’m interested in working on this issue. Could you please assign it to me?
Thank you!

**Comment by cosmiiccat** [comment]
Hi @AndersAskeland,

I have completed the changes for the issue and have submitted a pull request. Could you please review it when you get a chance?
