### ISSUE TITLE
Update admiral version in DESCRIPTION file

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiralmetabolic#4]
### Background Information

Currently, DESCRIPTION file records a dependency on admiral 1.1.0. But this version has a bug, and admiral 1.1.1 is due to release imminently. Once this happens, the DESCRIPTION file should be updated to point to it.

### Definition of Done

Update DESCRIPTION file with following line `admiral (>= 1.1.1)` in place of existing one.

**Comment by AndersAskeland** [comment]
Admiral 1.1.1 is now [released](https://github.com/pharmaverse/admiral/releases/tag/v1.1.1).

**Comment by manciniedoardo** [comment]
> Admiral 1.1.1 is now [released](https://github.com/pharmaverse/admiral/releases/tag/v1.1.1).

Thanks @AndersAskeland - do you want to give this a go?

**Comment by AndersAskeland** [comment]
Can do!
