### ISSUE TITLE
Vignette: CoEQ ADaM (ADCOEQ?)

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiralmetabolic#40]
### Background Information

Once #39 is completed, we will have test data for CoEQ. Then we can make a vignette explaining how to categorise/group the data. this may inform whether we want to make specific  new functions or whether existing {admiral} functionality (see [questionnaires user guide](https://pharmaverse.github.io/admiral/dev/articles/questionnaires.html)) is enough.

### Definition of Done

- [ ] Agree dataset name (ADCOEQ?)
- [ ] Create vignette
- [ ] Ensure that right at the top of the vignette we have text to the effect of: _UoLeeds is the license holder and any parties wishing to use the CoEQ questionnaire need to purchase the license (at the appropriate link)_ (precise wording to be agreed with UoLeeds).
- [ ] Make any requests for new {admiralmetabolic} functions.

**Comment by AndersAskeland** [comment]
@kathrinflunkert I would also love to take a look :) A great way to highlight ongoing changes is to make a "Draft pull request". It is created in the same way as a normal pull request, but you can click the draft option. The draft pull request will automatically update, when you make subsequent changes, and when it possible to change it to a normal pull request when its ready for review. Please also let me know if I should help with setting it up.

**Comment by kathrinflunkert** [comment]
@AndersAskeland Sure, please feel free to review as well. I created a draft pull request right now.
