### ISSUE TITLE
Test data: VS enhancement for epigastric weight

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiralmetabolic#42]
### Background Information

@starosto mentioned that it's possible that we could we add epigastric weight (pending her confirmation) to our test data and vignette/template.

### Definition of Done

- [ ] @starosto to confirm
- [ ] update `vs_metabolic` with new test
- [ ] update vignette lookup table to map new test (if applicable)
- [ ] update template to deal with new parameter (if applicable)

**Comment by manciniedoardo** [comment]
@starosto any updates here?

**Comment by starosto** [comment]
@manciniedoardo  It seems that it is rather not a commonly used parameter. There is no need to expand the vignette to include this context, at least for now.
