### ISSUE TITLE
Ensure test coverage of {admiralmetabolic} is 100% (or close!)

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiralmetabolic#43]
### Background Information

Use [covr](https://covr.r-lib.org/) to generate test coverage report. On hold until #31 is closed.

### Definition of Done

Ensure test coverage is 100% or very close by ensuring existing tests (and/or any new tests that are written) execute every line of the functions.

**Comment by yurovska** [comment]
Could somebody check why coverage PR comments fail to be added?

![image](https://github.com/user-attachments/assets/cc7b7681-3933-4a0b-81fe-f04c6ae72e14)

**Comment by yurovska** [comment]
> Could somebody check why coverage PR comments fail to be added?
> 
> ![image](https://private-user-images.githubusercontent.com/182518857/382277032-cc7b7681-3933-4a0b-81fe-f04c6ae72e14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MzAzODQsIm5iZiI6MTczMDgzMDA4NCwicGF0aCI6Ii8xODI1MTg4NTcvMzgyMjc3MDMyLWNjN2I3NjgxLTM5MzMtNGEwYi04MWZlLWYwNGM2YWU3MmUxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxODA4MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTk4MTEyZTM2NTFlOTM1MDE3ZjNmMGZmZDQyZTQzMDVlMmZhYzczNDk0YjI0ZjFhYmNlOTIwNmEwZWJhOWNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jBq4Ck_XLhWpDLHDhYqQfs5MgBuBpki2RRoPScm88Dk)

I think the reason was that I was working on the PR from the fork. No issue if a branch is created within the repo itself.

**Comment by manciniedoardo** [comment]
Closing now as we are at 100%. Well done @yurovska on writing some great tests!

![image](https://github.com/user-attachments/assets/49564960-66e9-4830-83ca-cc4494da167e)
