### ISSUE TITLE
Documentation:  Update `NEWS.md`  ahead of first release

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiralmetabolic#48]
### Let us know where something needs a refresh or put your idea here!

The `NEWS.md` file populates the changelog tab on the admiralmetabolic website. It usually contains updates on what's changed during successive releases of the package. See for example the [{admiral} changelog](https://pharmaverse.github.io/admiral/news/index.html). However, when you are working towards the first release, there is no need to populate `NEWS.md` as everything is new.  Currently, our `NEWS.md` is just the default one coming from {admiraltemplate}/

We need to update `NEWS.md` so that it indicates that {admiralmetabolic} 0.1.0 will be the first release of the package. See for example the [{admiralpeds}](https://pharmaverse.github.io/admiralpeds/news/index.html) `NEWS.md`:

![image](https://github.com/user-attachments/assets/3735fe30-ed7b-4813-bfbc-3530a8d8f9c8)

**Comment by manciniedoardo** [comment]
@kiwi5104679 this might be a good one for you/ I've assigned it to you if you wanna try it out?

**Comment by kiwi5104679** [comment]
Thank you @manciniedoardo , I'll take it.

**Comment by manciniedoardo** [comment]
As discussed by chat, aim to have this complete by 20th Nov.

**Comment by AndersAskeland** [comment]
@kiwi5104679 how is it going with this? Do you need some support?

**Comment by kiwi5104679** [comment]
Hi @AndersAskeland, @manciniedoardo.
Sorry to respond late.

I need your help.
devtools::check() and pkgdown::build_site() do not work.
The cause seems that the function derive_vars_cat() is used but cannot be found.
In my understanding, the function derive_vars_cat() does not exist in latest version of {admiral} so far.
![image](https://github.com/user-attachments/assets/59402a29-72fb-4eca-9561-03248bdaf854)

Is there any way to remove this error?
Please let me know if my understanding is not correct.

**Comment by manciniedoardo** [comment]
Hi @kiwi5104679, this is happening because your installed version of {admiral} is probably the latest  CRAN version (1.1) rather than the latest development version. You can check this by running `packageVersion("admiral")`. To install the latest development version, where `derive_vars_cat()` is present, you need to run: `devtools::install_github("pharmaverse/admiral", ref = "main")`. This is the version of the package that will be released in January and so we want to be good relative to that version, since we'll release a few weeks after it.

**Comment by manciniedoardo** [comment]
By the way, [from your PR](https://github.com/pharmaverse/admiralmetabolic/pull/55#issuecomment-2486251945) you can see that the checks pass in our CICD environment where we have the right version installed each time

**Comment by kiwi5104679** [comment]
Hi @manciniedoardo , @AndersAskeland .
I appreciate your supports!
Thanks to your help, I could install the latest {admiral} in GitHub and run build_site() and check().
I updated [PR](https://github.com/pharmaverse/admiralmetabolic/pull/55) so please review it.

I'm not sure whether my wording in NEWS is good or not.
