### ISSUE TITLE
Bug: All `OSORRES` in `qs_metabolic` assigned as `2` 

### ISSUE THREAD

**Issue by AndersAskeland** [pharmaverse/admiralmetabolic#54]
### What happened?

The `qs_metabolic` dataset contains the value 2 for all records in `OSORRES`.

The bug is related to the mutate statement for `OSORRES` where we assign `OSORRES` using a non-vectorized method (see below). We would need to change this function to either a vectorized function, or change to rowwise operations in the entire mutate call using `dplyr::rowwise()`.

```r
qs_metabolic_results <- qs_metabolic_shell %>%
  mutate(
    DOMAIN = "QS",
    QSORRES = floor(runif(1) * 10) + round(runif(1)), # the function in question
    QSORRESU = "cm",
    QSSTRESU = "cm",
    QSSTRESN = QSORRES,
    QSSTRESC = as.character(QSORRES),
    QSBLFL = ifelse(VISIT == "BASELINE", "Y", NA_character_)
  )
```

**Comment by AndersAskeland** [comment]
@pharmaverse/admiralmetabolic A good first issue if there are any takers :)

**Comment by kathrinflunkert** [comment]
@AndersAskeland I don't think you have been looking at the latest version. QSORRESU is not "cm" anymore but "mm" and also the bug that all values where 2 had been resolved in the final version.

**Comment by AndersAskeland** [comment]
Woops… you’re right. I was on the wrong branch 😅
